=== sunaoka/japanpost-international-mail/dist/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "array",
    "title": "Japan Post's International Mail Service availability by country",
    "items": {
        "type": "object",
        "required": [
            "countryCode",
            "destination",
            "letterPost",
            "parcels",
            "ems",
            "restrictions",
            "notification"
        ],
        "properties": {
            "countryCode": {
                "type": "string",
                "title": "Country code (ISO 3166-1 Alpha-2 and assigned by Japan Post)"
            },
            "destination": {
                "type": "string",
                "title": "Destination"
            },
            "letterPost": {
                "type": "object",
                "title": "Letter-post",
                "required": [
                    "air",
                    "sal",
                    "surface"
                ],
                "properties": {
                    "air": {
                        "type": "string",
                        "title": "Letter-post (Air)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    },
                    "sal": {
                        "type": "string",
                        "title": "Letter-post (SAL)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    },
                    "surface": {
                        "type": "string",
                        "title": "Letter-post (Surface)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    }
                }
            },
            "parcels": {
                "type": "object",
                "title": "Parcels",
                "required": [
                    "air",
                    "sal",
                    "surface"
                ],
                "properties": {
                    "air": {
                        "type": "string",
                        "title": "Parcels (Air)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    },
                    "sal": {
                        "type": "string",
                        "title": "Parcels (SAL)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    },
                    "surface": {
                        "type": "string",
                        "title": "Parcels (Surface)",
                        "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
                    }
                }
            },
            "ems": {
                "type": "string",
                "title": "EMS",
                "enum": ["acceptable", "some_acceptable", "not_acceptable", "no_service"]
            },
            "restrictions": {
                "type": "object",
                "title": "Restrictions, and Delays in Japan",
                "required": [
                    "normal",
                    "temporary",
                    "delays"
                ],
                "properties": {
                    "normal": {
                        "type": "array",
                        "title": "Restrictions in the normal period",
                        "items": {
                            "type": "string"
                        }
                    },
                    "temporary": {
                        "type": "array",
                        "title": "Temporary restrictions caused by the novel coronavirus pandemic",
                        "items": {
                            "type": "string"
                        }
                    },
                    "delays": {
                        "type": "array",
                        "title": "Delays in Japan",
                        "items": {
                            "type": "string"
                        }
                    }
                }
            },
            "notification": {
                "type": "string",
                "title": "Precautions concerning delivery and other matters after mail items arrive in the destination countries and territories (Contents of notification from foreign postal operators)"
            }
        }
    }
}

=== sunaoka/japanpost-international-mail/dist/en.json
[{"countryCode":"","destination":"China","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":"Significant delays will be experienced in the delivery of inbound mail products due to the restriction for the novel coronavirus pandemic. Affected areas: Chongqing, Guangxi Zhuang, Guangdong, Guizhou, Hainan, Hubei, Hunan, Sichuan, Yunnan"},{"countryCode":"","destination":"United States of America","letterPost":{"air":"some_acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"not_acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":["EMS items to some regions are not acceptable."],"temporary":["Among Air items, only some letter-post items are accepted. Check \"Acceptance\/non-acceptance of international mail to the United States, etc.\" for details."],"delays":["Due to reduction or suspension of flights, considerable time will be needed for delivery of items to their destination."]},"notification":"Please note that considerable delivery delays are expected due to a large increase in inbound postal items in U.S. Under the circumstances, items will not be handed directly to addressees."},{"countryCode":"","destination":"Republic of Korea","letterPost":{"air":"acceptable","sal":"no_service","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"no_service","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":"Delays will be experienced in the delivery of mail items in the country (territory). Items will not be handed directly to addressees in the following area. Affected area: Daegu"},{"countryCode":"","destination":"Philippines","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":["EMS items to some regions are not acceptable."],"temporary":[],"delays":["Loading items onto airplanes is expected to take about two to three weeks due to the shortage of loading space caused by the reduction of flights."]},"notification":"International mail processing centers are operating with a skeleton workforce in order to accept inbound mail items. Therefore, delivery delays will be experienced in the country (territory). Only postal items containing cheques or medical supplies will be delivered to quarantine areas."},{"countryCode":"","destination":"Taiwan","letterPost":{"air":"acceptable","sal":"no_service","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"no_service","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":""},{"countryCode":"","destination":"Hong Kong","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":""},{"countryCode":"","destination":"Australia","letterPost":{"air":"some_acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"not_acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"not_acceptable","restrictions":{"normal":["EMS items to some regions are not acceptable."],"temporary":["Among Air items, only some letter-post items are accepted. Check \"Acceptance\/non-acceptance of international mail to the United States, etc.\" for details."],"delays":[]},"notification":"Delays will be experienced in the delivery of mail items in the country (territory), and items will not be handed directly to addressees."},{"countryCode":"","destination":"Thailand","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":"Delays will be experienced in the delivery of mail items in the country (territory)."},{"countryCode":"","destination":"Great Britain","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":["Transportation of outbound mails to the destination is expected to take considerable time due to the shortage of cargo space caused by the reduction of flights."]},"notification":"Items will not be handed directly to addressees."},{"countryCode":"","destination":"Singapore","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":"Items will not be handed directly to addressees, so writing the addressee's phone number on the item is recommended."},{"countryCode":"","destination":"Iceland","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":"Delays will be experienced in the delivery of mail items in the country (territory), and items will not be handed directly to addressees."},{"countryCode":"","destination":"Ireland","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":["Loading mail items onto airplanes is expected to take considerable time due to the shortage of cargo space caused by the reduction of flights."]},"notification":"Items will not be handed directly to addressees."},{"countryCode":"","destination":"Azerbaijan","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"not_acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"not_acceptable"},"ems":"not_acceptable","restrictions":{"normal":["EMS items to some regions are not acceptable."],"temporary":[],"delays":[]},"notification":""},{"countryCode":"","destination":"Ascension","letterPost":{"air":"not_acceptable","sal":"no_service","surface":"acceptable"},"parcels":{"air":"no_service","sal":"no_service","surface":"acceptable"},"ems":"no_service","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":""},{"countryCode":"","destination":"Afghanistan","letterPost":{"air":"acceptable","sal":"no_service","surface":"not_acceptable"},"parcels":{"air":"acceptable","sal":"no_service","surface":"not_acceptable"},"ems":"no_service","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":""},{"countryCode":"","destination":"United Arab Emirates","letterPost":{"air":"not_acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"not_acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"not_acceptable","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":""},{"countryCode":"","destination":"Algeria","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":["Loading mail items onto airplanes is expected to take considerable time due to the shortage of cargo space caused by the reduction of flights."]},"notification":""},{"countryCode":"","destination":"Argentina","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"not_acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"not_acceptable"},"ems":"acceptable","restrictions":{"normal":[],"temporary":[],"delays":["Loading mail items onto airplanes is expected to take considerable time due to the shortage of cargo space caused by the reduction of flights."]},"notification":"Delays will be experienced in the delivery of mail items in the country (territory), and items will not be handed directly to addressees."},{"countryCode":"","destination":"Aruba","letterPost":{"air":"acceptable","sal":"no_service","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"no_service","surface":"acceptable"},"ems":"no_service","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":""},{"countryCode":"","destination":"Albania","letterPost":{"air":"acceptable","sal":"no_service","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"no_service","surface":"acceptable"},"ems":"no_service","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":"Delays will be experienced in the delivery of mail items in the country (territory)."},{"countryCode":"","destination":"Armenia","letterPost":{"air":"acceptable","sal":"not_acceptable","surface":"not_acceptable"},"parcels":{"air":"acceptable","sal":"not_acceptable","surface":"not_acceptable"},"ems":"no_service","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":"Considerable delays will be experienced in the delivery of mail items in the country (territory), and items will not be handed directly to addressees."},{"countryCode":"","destination":"Anguilla","letterPost":{"air":"acceptable","sal":"no_service","surface":"acceptable"},"parcels":{"air":"acceptable","sal":"no_service","surface":"not_acceptable"},"ems":"no_service","restrictions":{"normal":[],"temporary":[],"delays":[]},"notification":""},{"countryCode":"","destination":"Angola","letterPost":{"air":"acceptable","sal":"no_service","surface":"not_acceptable"},"parcels":{"air":"acceptable","sal":"no_service","surface":"not_acceptable"},"ems":"no_service","restrictions":{"normal":[],"temporary":[],"delays
